Check date of POLICY file; remove toplevel files.

diff --git a/bin/cleanup-history b/bin/cleanup-history
--- a/bin/cleanup-history
+++ b/bin/cleanup-history
@@ -5,19 +5,11 @@
 # We must retain older revisions if they have never been changed or
 # have been changed just some days ago.
 #
-# Only files under RCS/owner can be cleaned up. Toplevel files must
-# be left unchanged, because old revisons may still be referenced from
-# older files under RCS/owner.
+# Files under RCS/owner are cleaned up first.
+# Find oldest POLICY file of any owner.
+# Then clean up old toplevel files not referenced from files under RCS/owner.
 
 usage () { echo "Usage: $0 <export_dir>"; }
-
-# Bug:
-# Wir können Änderungen an "visible" haben, ohne dass das zu einem Diff führt.
-# ==> neuer Algorithmus erforderlich:
-# - das Datum von POLICY bestimmen
-# - dann von den anderen Dateien die neueste Version vor diesem Dateum behalten
-# ==> dann können wir auch gleich das älteste dateum aller POLICY bestimmen
-# und entsprechend die globalen Dateien bereinigen.
 
 # This must be understood by "date" command.
 old='1 year ago'
@@ -36,16 +28,48 @@ debug () { echo $1; }
 
 old_date=$(date -R -d "$old")
 
+# Oldest POLICY file of all owners
+oldest_epoch=$(date -d "$old" +'%s')
+collect_oldest_epoch () {
+    local epoch=$(date --date "$1" +'%s') || abort "Can't analyze $1"
+    if [ $epoch -lt $oldest_epoch ] ; then
+        oldest_epoch=$epoch
+    fi
+}
 
-# Cleanup only owner/* directories.
+outdate () {
+    local file="$1"
+    local o_date="$2"
+    local o1_rev o_rev
+
+    # Show two newest revisions older than $p_date.
+    # First revision will be retained.
+    # Next older revision will be removed.
+    line=$(rlog -d"$o_date>=" -zLT $file|
+        head -20|grep '^revision'|head -2|cut -d' ' -f2|paste -s -d' ')
+    read o1_rev o_rev <<EOF
+$line
+EOF
+
+    # No next older revision found
+    [ -z "$o_rev" ] && return
+
+    # Remove from beginning of branch (oldest) up to and
+    # including old revison
+    debug "Removing up to $o_rev in $file"
+    rcs -q -o:$o_rev $file
+}
+
+# First check owner/* directories.
 for dir in $RCS/owner/* ; do
+    p_file=$dir/POLICY,v
 
-    # Check if owner has already been removed before $old.
+    # Check if owner has already been deleted.
+    # History can be removed if it wasn't changed since $old.
     c_dir=$(echo $dir|sed -e "s|$RCS|$current|")
     if [ ! -d "$c_dir"  ] ; then 
 
-        # Find newest revision newer than $old
-        p_file=$dir/POLICY,v
+        # Find newest revision newer than $old_date
         p_rev=$(rlog -d"$old_date<" -zLT $p_file|
             head -14|tail -1|grep '^revision') || true
         if [ -z "$p_rev" ] ; then
@@ -57,23 +81,24 @@ for dir in $RCS/owner/* ; do
         fi
     fi
 
+    # Find newest revision of POLICY older than $old_date.
+    p_rev=$(rlog -d"$old_date>=" -zLT $p_file|
+        head -14|grep '^revision'|head -1|cut -d' ' -f2) || continue
+
+    # Identify date of newest revision of POLICY older than $old_date.
+    p_date=$(rlog -r$p_rev -zLT $p_file|grep '^date:'|cut -d' ' -f2-3|cut -d';' -f1)
+    collect_oldest_epoch "$p_date"
+
     for file in $(find $dir/ -name '*,v') ; do
-
-        # Show two newest revisions older than $old.
-        # First revision will be retained.
-        # Next older revision will be removed.
-        line=$(rlog -d"$old_date>=" -zLT $file|
-            head -20|grep '^revision'|head -2|cut -d' ' -f2|paste -s -d' ')
-        read o1_rev o_rev <<EOF
-$line
-EOF
-
-        # No next older revision found
-        [ -z "$o_rev" ] && continue
-
-        # Remove from beginning of branch (oldest) up to and
-        # including old revison
-        debug "Removing up to $o_rev in $file"
-        rcs -q -o:$o_rev $file
+        outdate $file "$p_date"
     done
+done
+
+oldest_date=$(date -R -d @$oldest_epoch)
+debug "Oldest owner POLICY: $oldest_date"
+
+# Next check topelevel files.
+for file in $RCS/* ; do
+    [ -d "$file" ] && continue
+    outdate $file "$oldest_date"
 done
